import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "next-themes";
import { LanguageProvider, useLanguage } from "../context/LanguageContext";
import { Noto_Sans_Oriya, Figtree } from "next/font/google";

// Font setup
const noto = Noto_Sans_Oriya({
  subsets: ["latin"],
  display: "swap",
});

const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto.className /* or figtree.className */}>
        {/* Ensure ThemeProvider and LanguageProvider are handling SSR */}
        <ThemeProvider defaultTheme="system" attribute="class">
          <LanguageProvider>{children}</LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
